Update generate-assets-packagist.yml

diff --git a/.github/workflows/generate-assets-packagist.yml b/.github/workflows/generate-assets-packagist.yml
--- a/.github/workflows/generate-assets-packagist.yml
+++ b/.github/workflows/generate-assets-packagist.yml
@@ -1,55 +1,60 @@
 name: Build and Publish Plugin
 
 on:
-  workflow_dispatch:  # This allows manual triggering from the GitHub UI
-  push:
-      branches:
-        - main   # Or the branch you want to trigger it for, like 'main' or 'master'
+  workflow_dispatch:  # Manual trigger from GitHub UI
   #push:
-    # Trigger on pushing a tag (e.g., v1.0.0)
-    #tags:
-     # - 'v*'
+    #branches:
+      #- main  # Trigger on push to the main branch
 
 jobs:
-  build:
+  generate-assets:
     runs-on: ubuntu-latest
-
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v2
+      - name: Checkout repository
+        uses: actions/checkout@v2
 
-    - name: Set up Node.js
-      uses: actions/setup-node@v2
-      with:
-        node-version: '22'  # Adjust to your required Node.js version
+      - name: Set up Node.js
+        uses: actions/setup-node@v2
+        with:
+          node-version: '22'  # Adjust to your required Node.js version
 
-    - name: Install dependencies and generate Assets
-      run: |
-        sudo apt-get update
-        sudo apt-get install -y make  # Install make utility if it's not available by default
-        make init skip-composer  # Run your custom Makefile command
+      - name: Install dependencies and generate assets
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y make  # Install make utility if it's not available by default
+          make init skip-composer  # Run your custom Makefile command
 
-    - name: Verify the contents of the repository and dist folder
-      run: |
-        ls -l
-        echo "Contents of assets/dist folder:"
-        ls assets/dist/
+      - name: Verify the contents of the repository and dist folder
+        run: |
+          echo "Contents of assets/dist folder:"
+          ls assets/dist/
 
-    - name: Commit dist folder
-      run: |
-        # Ensure that dist/ folder exists after build
-        if [ -d "assets/dist" ]; then
-          git config --global user.name "puyaalexxx"
-          git config --global user.email "puyaalexxx@gmail.com"
-          git add assets/dist/
-          git commit -m "Add dist folder for release" || echo "No changes to commit"
-          git push origin HEAD:main  # Push the changes back to the main branch
-        else
-          echo "assets/dist/ folder not found after build, skipping commit."
-        fi
+  commit-changes:
+    runs-on: ubuntu-latest
+    needs: generate-assets  # This job depends on the generate-assets job
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
 
-    - name: Create release on Packagist
-      run: |
-        curl -u "${{ secrets.PACKAGIST_TOKEN }}" -X POST -d '{"repository": "https://github.com/puyaalexxx/devhunters-fw"}' https://packagist.org/api/submit
-      env:
-        PACKAGIST_TOKEN: ${{ secrets.PACKAGIST_TOKEN }}  # Access the secret from GitHub
+      - name: Commit dist folder
+        run: |
+          # Ensure that dist/ folder exists after build
+          if [ -d "assets/dist" ]; then
+            git config --global user.name "puyaalexxx"
+            git config --global user.email "puyaalexxx@gmail.com"
+            git add -f assets/dist/  # Force add the dist folder even if it's ignored in .gitignore
+            git commit -m "Add dist folder for release" || echo "No changes to commit"
+            git push origin HEAD:main  # Push the changes back to the main branch
+          else
+            echo "assets/dist/ folder not found after build, skipping commit."
+          fi
+
+  create-packagist-release:
+    runs-on: ubuntu-latest
+    needs: commit-changes  # This job depends on the commit-changes job
+    steps:
+      - name: Create release on Packagist
+        run: |
+          curl -u "${{ secrets.PACKAGIST_TOKEN }}" -X POST -d '{"repository": "https://github.com/puyaalexxx/devhunters-fw"}' https://packagist.org/api/submit
+        env:
+          PACKAGIST_TOKEN: ${{ secrets.PACKAGIST_TOKEN }}  # Access the secret from GitHub
